logging:
  level:
    root: info

# 配置发送方信息
spring:
  mail:
    host: smtp.163.com
    username: huangbangbang666@163.com
    password: VQBNSYPTJBAOUXRR                   # 填写客户端的授权码
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  redis:
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 500
          min-idle: 0
      lettuce:
        shutdown-timeout: 30000
